### ISSUE TITLE
npm run deploy:prod 报错

### ISSUE THREAD

**Issue by cnkerry** [bodyno/react-starter-kit#20]
npm start/npm run compile 都正常，npm run deploy:prod 报错
是我还需要配置什么吗？

0 info it worked if it ends with ok
1 verbose cli [ 'C:\Program Files\nodejs\node.exe',
1 verbose cli   'C:\Users\kerry\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'deploy:prod' ]
2 info using npm@3.10.8
3 info using node@v4.4.7
4 verbose run-script [ 'predeploy:prod', 'deploy:prod', 'postdeploy:prod' ]
5 info lifecycle react-starter-kit@0.2.0~predeploy:prod: react-starter-kit@0.2.0
6 silly lifecycle react-starter-kit@0.2.0~predeploy:prod: no script for predeploy:prod, continuing
7 info lifecycle react-starter-kit@0.2.0~deploy:prod: react-starter-kit@0.2.0
8 verbose lifecycle react-starter-kit@0.2.0~deploy:prod: unsafe-perm in lifecycle true
9 verbose lifecycle react-starter-kit@0.2.0~deploy:prod: PATH: C:\Users\kerry\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;E:\11_react\react-starter-kit-cn\node_modules.bin;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\TortoiseSVN\bin;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\ManagementStudio\;C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn\;C:\Users\kerry.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files (x86)\VisualSVN\bin;C:\Program Files (x86)\CodeSmith\v6.5\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\Microsoft\Web Platform Installer\;C:\Program Files (x86)\Microsoft ASP.NET\ASP.NET Web Pages\v1.0\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files\Microsoft SQL Server\110\DTS\Binn\;C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.0\;C:\Program Files\nodejs\;C:\Program Files\Git\cmd;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\dotnet\;C:\Users\kerry\AppData\Roaming\npm
10 verbose lifecycle react-starter-kit@0.2.0~deploy:prod: CWD: E:\11_react\react-starter-kit-cn
11 silly lifecycle react-starter-kit@0.2.0~deploy:prod: Args: [ '/d /s /c', 'better-npm-run deploy:prod' ]
12 silly lifecycle react-starter-kit@0.2.0~deploy:prod: Returned: code: 1  signal: null
13 info lifecycle react-starter-kit@0.2.0~deploy:prod: Failed to exec deploy:prod script
14 verbose stack Error: react-starter-kit@0.2.0 deploy:prod: `better-npm-run deploy:prod`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Users\kerry\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at EventEmitter.emit (events.js:172:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Users\kerry\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at ChildProcess.emit (events.js:172:7)
14 verbose stack     at maybeClose (internal/child_process.js:827:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid react-starter-kit@0.2.0
16 verbose cwd E:\11_react\react-starter-kit-cn
17 error Windows_NT 10.0.10586
18 error argv "C:\Program Files\nodejs\node.exe" "C:\Users\kerry\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js" "run" "deploy:prod"
19 error node v4.4.7
20 error npm  v3.10.8
21 error code ELIFECYCLE
22 error react-starter-kit@0.2.0 deploy:prod: `better-npm-run deploy:prod`
22 error Exit status 1
23 error Failed at the react-starter-kit@0.2.0 deploy:prod script 'better-npm-run deploy:prod'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the react-starter-kit package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     better-npm-run deploy:prod
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs react-starter-kit
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls react-starter-kit
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by cnkerry** [comment]
已解决。
是我没有安装 babel-react-optimize
